# Generated by Django 6.1.1 on 2026-09-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=20)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Weding Planning", "Wedding Planning"),
                            (
                                "Pre_wedding and Engagement",
                                "Pre_wedding and Engagement",
                            ),
                            ("Birthday Celebration", "Birthday Celebration"),
                            ("Corporate Event", "Corporate Event"),
                            (
                                "Galas and Award Ceremonies",
                                "Galas and Award Ceremonies",
                            ),
                            ("Destination Celebration", "Destination Celebration"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
