# Generated by Django 6.1.1 on 2026-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact_form",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
